import Head from 'next/head'
import CardTodoList from '../components/CardTodoList';
import styles from '../styles/Home.module.sass'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Todo App</span>
        </h1>
        <CardTodoList/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.facebook.com/ryan.vo.0106"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Ryan Võ
        </a>
      </footer>
    </div>
  );
}
